---
- name: Ensure Xorg directory exists
  file:
    path: /etc/X11/xorg.conf.d/
    state: directory
    mode: 0755

- name: Deploy Xorg config
  become: true
  copy:
    src: "{{ item }}"
    dest: /etc/X11/xorg.conf.d/
    owner: root
    group: root
    mode: 0644
  with_fileglob: "files/*"
