#!/bin/sh

while read file
do
  case "$1" in
    "w") set_wallpaper "$file" ;;
    "d") rm "$file" ;;
    "s") curl -F "file=@$file" 0x0.st | xclip -sel c ;;
    "g") setsid -f gimp "$file" ;;
  esac
done

