exec-once = ghostty

exec-once = waybar
exec-once = swww-daemon --format xrgb --no-cache
exec-once = set_wallpaper
exec-once = playerctld

exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

exec-once = systemctl --user enable --now easyeffects
# exec-once = quickshell -p ~/.config/quickshell/Main.qml
exec-once = quickshell

exec-once = pypr
exec-once = swaync
exec-once = swaync-client -df
exec-once = udiskie
