---
- name: the good shit
  become: true
  pacman: name={{ item }} state=latest
  with_items:
    - curl
    - git
    - htop
    - jq
    - python
    - python-pip
    - stow
    - tmux
    - tree
    - wget
