---
- name: update cache
  pacman:
    update_cache: yes

- name: The good shit
  become: true
  pacman: name={{ item }} state=latest
  with_items:
    - curl
    - git
    - htop
    - jq
    - nodejs
    - npm
    - python
    - python-pip
    - python-pipx
    - rustup
    - stow
    - tmux
    - tree
    - wget

- name: Setup rustup
  command: rustup default stable
