---
- name: The linux experience baby
  become: true
  pacman: name={{ item }} state=latest
  with_items:
    - bluez
    - bluez-utils
    - chromium
    - dunst
    - firefox
    - fzf
    - gimp
    - lf
    - maim
    - mpd
    - mpv
    - nautilus
    - ncmpcpp
    - neovim
    - nsxiv
    - pamixer
    - python-pywal
    - ripgrep
    - slock
    - sxhkd
    - ueberzug
    - xclip
    - xcompmgr
    - xdotool
    - xorg-xrandr
    - xorg-xsetroot
    - xwallpaper
    - zsh-syntax-highlighting

- name: Create user directories
  file:
    path: "~/{{ item }}"
    state: directory
  loop:
    - dl
    - dox
    - music
    - pix/ss
    - pix/wall
    - pub
    - vids
    - .local/bin
    - .local/share
    - .local/src
