#!/usr/bin/env sh
alias \
    ytbdl="nix run nixpkgs#yt-dlp -- -f bestvideo+bestaudio -o '%(title)s.%(ext)s' --external-downloader=aria2c" \
    ytadl="nix run nixpkgs#yt-dlp -- -x -f bestaudio -o '%(title)s.%(ext)s' --external-downloader=aria2c" \
    ytdl="nix run nixpkgs#yt-dlp -- -f best -o '%(title)s.%(ext)s' --external-downloader=aria2c" \
    ytpdl="nix run nixpkgs#yt-dlp -- -f best -o '%(playlist_index)s. %(title)s.%(ext)s' --external-downloader=aria2c" \

alias \
    hst="history 1 -1 | cut -c 8- | sort | uniq | fzf --layout reverse | tr -d '\n' | xclip -sel c" \
    my_ip="ip address | grep -o \"inet 192.*/\" | awk '{ print \$2 }' | tr / ' ' | xargs" \
    xsc="xclip -selection clipboard" \

alias \
    fzf="fzf --layout reverse" \
    python="python3" \
    sqlite="sqlite3" \
    sxiv="nsxiv" \
    vim="nvim" \

alias \
    ip="ip -color=auto" \
    free="free -h" \
    du="du -h" \
    df="df -h" \

alias nix-shell="nix-shell --run zsh"
