save-position-on-quit=yes

hwdec=auto
interpolation=yes
tscale=oversample
video-sync=display-resample

volume=100
volume-max=150
audio-delay=0.0

osc=yes
keep-open=yes
autofit=80%
cursor-autohide=1000
osd-duration=2000

script-opts=ytdl_hook-ytdl_path=/usr/bin/yt-dlp
#ytdl-format=bestvideo[height<=1080]+bestaudio
