---
- name: Stow dotfiles
  shell: stow -d ~/.dotfiles -t ~ .

- name: Symlink profile
  file:
    src: ~/.config/shell/profile
    dest: ~/.zprofile
    state: link

- name: Symlink xinitrc
  file:
    src: ~/.config/x11/xinitrc
    dest: ~/.xinitrc
    state: link
