---
- name: Ensure ssh is installed
  become: true
  pacman:
    name: openssh
    state: present

- name: Enable ssh daemon
  become: true
  systemd:
    name: sshd
    state: started
    enabled: yes

- name: "Create .ssh"
  file:
    path: "~/.ssh"
    state: directory
    mode: '0755'

- name: generate SSH key "id_rsa"
  openssh_keypair:
    path: "~/.ssh/id_rsa"
    type: rsa
    size: 4096
    state: present
    force: no
