source = ~/.cache/wal/colors.conf
source = ~/.config/hypr/custom/colors.conf
source = ~/.config/hypr/custom/env.conf
source = ~/.config/hypr/custom/execs.conf
source = ~/.config/hypr/custom/general.conf
source = ~/.config/hypr/custom/keybinds.conf
source = ~/.config/hypr/custom/rules.conf
