#!/bin/sh

while read file
do
  case "$1" in
    "w") set_wallpaper "$file" ;;
    "d") rm "$file" ;;
    "s") curl -F "file=@$file" 0x0.st | wl-copy ;;
    "g") setsid -f gimp "$file" ;;
    "p") scp $file phone:~/storage/pictures/Screenshots ;;
  esac
done
