---
- name: Get dmenu
  git:
    repo: https://github.com/lazyfiki/dmenu.git
    dest: ~/.local/src/dmenu

- name: Install dmenu
  become: true
  command: make install
  args:
    chdir: /home/{{ user }}/.local/src/dmenu
