---
- name: Get dwm
  git:
    repo: https://github.com/lazyfiki/dwm.git
    dest: ~/.local/src/dwm

- name: Install dwm
  become: true
  command: make install
  args:
    chdir: /home/{{ user }}/.local/src/dwm
