---
- name: Get st
  git:
    repo: https://github.com/lazyfiki/st.git
    dest: ~/.local/src/st

- name: install st
  become: true
  command: make install
  args:
    chdir: /home/{{ user }}/.local/src/st
