asterisk= "*";
prompt = "$";
font = "JetBrains Mono:size=11";
prompt_fg = "{background}";
prompt_bg = "{color4}";
normal_fg = "{color4}";
normal_bg = "{background}";
select_fg = "{color4}";
select_bg = "{background}";
desc_fg = "{background}";
desc_bg = "{color4}";
