---
- name: the linux experience baby
  become: true
  pacman: name={{ item }} state=latest
  with_items:
    - dunst
    - fzf
    - gimp
    - lf
    - maim
    - mpd
    - mpv
    - nautilus
    - ncmpcpp
    - neovim
    - nsxiv
    - python-pywal
    - ripgrep
    - slock
    - sxhkd
    - ueberzug
    - xclip
    - xcompmgr
    - xdotool
    - xwallpaper
    - zsh-syntax-highlighting
